services:
  mongo:
    image: mongo:6
    container_name: liquiverde-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  api:
    build: ./api
    container_name: liquiverde-api
    ports:
      - "3000:3000"
    env_file: ./api/.env
    depends_on:
      - mongo
    volumes:
      - ./data:/app/data
    restart: always

  web:
    build: ./web
    container_name: liquiverde-web
    ports:
      - "5173:5173"
    env_file: ./web/.env
    depends_on:
      - api
    # 👇 IMPORTANTE: agregar esto
    command: npm run dev -- --host
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always

volumes:
  mongo_data:
